spring:
#  default Config
  application:
    name: realworld_java
# db Config
  datasource:
    url: jdbc:sqlserver://172.20.1.5:1433;databaseName=study_for_spring
    username: seedvdidb
    password: Vdi@dm1n
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    prefix: resources/
    suffix: .html
    view-names:
      templates/*show-sql: false
